### ISSUE TITLE
Can't lint css file

### ISSUE THREAD

**Issue by soderlind** [gilbarbara/codeclimate-stylelint#1]
I'm very happy that you've created this add-on to codeclimate, but why can't I lint css files ?

I get, when I'm running `codeclimate analyze -e stylelint:beta`:

```bash
Starting analysis
Running stylelint: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine stylelint:beta failed with status 1 and stderr
No files to lint with the extensions: ".scss", ".less", ".sss".
See our documentation at https://docs.codeclimate.com/docs/stylelint for more information.
```

**Comment by soderlind** [comment]
btw, here's my `.codeclimate.yml`:

```yml
  stylelint:
    enabled: true
    config:
        config: .stylelintrc
        ignore_warnings: true
```

and here's my `.stylelintrc`:
```json
{
  "extends": "stylelint-config-wordpress"
}
```
.. I've added https://github.com/ntwb/stylelint-config-wordpress
